const randomKey = Math.random();
let quizData = [];
let pastResults = [];
let attemptsCount = 0;
let formChanged = false;
let newQuizNeeded = true;
let disagreeNum = 0;
let moduleSelectBoxes = [];
const placeholderExplanation = "No explanation available. Why don't you add one?"